/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioEditorRouteImport } from './routes/studio/editor'
import { Route as StudioFootageRouteImport } from './routes/studio/footage'
import { Route as StudioSetupRouteImport } from './routes/studio/setup'
import { Route as StudioVaryRouteImport } from './routes/studio/vary'
import { Route as StudioWallRouteImport } from './routes/studio/wall'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioEditorRoute = StudioEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => StudioRoute,
} as any)
const StudioFootageRoute = StudioFootageRouteImport.update({
  id: '/footage',
  path: '/footage',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSetupRoute = StudioSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => StudioRoute,
} as any)
const StudioVaryRoute = StudioVaryRouteImport.update({
  id: '/vary',
  path: '/vary',
  getParentRoute: () => StudioRoute,
} as any)
const StudioWallRoute = StudioWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/editor': typeof StudioEditorRoute
  '/studio/footage': typeof StudioFootageRoute
  '/studio/setup': typeof StudioSetupRoute
  '/studio/vary': typeof StudioVaryRoute
  '/studio/wall': typeof StudioWallRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/studio/editor': typeof StudioEditorRoute
  '/studio/footage': typeof StudioFootageRoute
  '/studio/setup': typeof StudioSetupRoute
  '/studio/vary': typeof StudioVaryRoute
  '/studio/wall': typeof StudioWallRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/editor': typeof StudioEditorRoute
  '/studio/footage': typeof StudioFootageRoute
  '/studio/setup': typeof StudioSetupRoute
  '/studio/vary': typeof StudioVaryRoute
  '/studio/wall': typeof StudioWallRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/studio'
    | '/studio/editor'
    | '/studio/footage'
    | '/studio/setup'
    | '/studio/vary'
    | '/studio/wall'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/studio/editor'
    | '/studio/footage'
    | '/studio/setup'
    | '/studio/vary'
    | '/studio/wall'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/studio'
    | '/studio/editor'
    | '/studio/footage'
    | '/studio/setup'
    | '/studio/vary'
    | '/studio/wall'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/editor': {
      id: '/studio/editor'
      path: '/editor'
      fullPath: '/studio/editor'
      preLoaderRoute: typeof StudioEditorRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/footage': {
      id: '/studio/footage'
      path: '/footage'
      fullPath: '/studio/footage'
      preLoaderRoute: typeof StudioFootageRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/setup': {
      id: '/studio/setup'
      path: '/setup'
      fullPath: '/studio/setup'
      preLoaderRoute: typeof StudioSetupRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/vary': {
      id: '/studio/vary'
      path: '/vary'
      fullPath: '/studio/vary'
      preLoaderRoute: typeof StudioVaryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/wall': {
      id: '/studio/wall'
      path: '/wall'
      fullPath: '/studio/wall'
      preLoaderRoute: typeof StudioWallRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioEditorRoute: typeof StudioEditorRoute
  StudioFootageRoute: typeof StudioFootageRoute
  StudioSetupRoute: typeof StudioSetupRoute
  StudioVaryRoute: typeof StudioVaryRoute
  StudioWallRoute: typeof StudioWallRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioEditorRoute: StudioEditorRoute,
  StudioFootageRoute: StudioFootageRoute,
  StudioSetupRoute: StudioSetupRoute,
  StudioVaryRoute: StudioVaryRoute,
  StudioWallRoute: StudioWallRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
